### ISSUE TITLE
Direction key input of the Dragon's Lair is Sensitive. The Bleep are the Bloop ??

### ISSUE THREAD

**Issue by OldGamers** [icculus/DirkSimple#18]
I really enjoyed playing this game a lot but the problem is that the arrow directions when I try to point to the right direction to grab the Rope he automatically lose the game dirt gets to burn every time I go and press the the direction key on my d-pad or keyboard I feel that the there's a bug involved but I'm not too sure because I'm not an expert in these kind of things but every time I press the right direction to get the Rope Dirk the daring keeps on falling off on the fire pit here's a video to show this demonstration and I feel that the keys are too sensitive when pressing the direction where dirt needs to go
https://www.youtube.com/watch?v=zaRKidB6Cpw

**Comment by icculus** [comment]
Bleep means "there was an accepted move, even if the move was wrong."  It buzzes when you try a move that the game ignores because there isn't any response programmed in for that move (try hitting the sword button in the flaming rope room, for example).

Moving right too early is a valid (but fatal!) move in the flaming rope room, so it bleeps. The arcade works the same, afaik.

The timing on the ropes, fwiw:

https://github.com/icculus/DirkSimple/blob/98cc3cd2d2627ff5b19bfe222967f081e6e8bc40/data/games/lair/game.lua#L581-L630

You have about a 750 millisecond window where you can correctly grab the next rope.

**Comment by OldGamers** [comment]
> Bleep means "there was an accepted move, even if the move was wrong." It buzzes when you try a move that the game ignores because there isn't any response programmed in for that move (try hitting the sword button in the flaming rope room, for example).
> 
> Moving right too early is a valid (but fatal!) move in the flaming rope room, so it bleeps. The arcade works the same, afaik.
> 
> The timing on the ropes, fwiw:
> 
> https://github.com/icculus/DirkSimple/blob/98cc3cd2d2627ff5b19bfe222967f081e6e8bc40/data/games/lair/game.lua#L581-L630
> 
> You have about a 750 millisecond window where you can correctly grab the next rope, starting 1.081 seconds after he starts swinging on the current rope.

omg your were 100% correct and I was delaying the right key command too early and I finally Past the rope part
